name: Retail App CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-scan:
    name: Code Quality and SAST
    runs-on: ubuntu-latest

    steps:
      # 1. Pull the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set up Python 3.14
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"

      # 3. Install dependencies and security tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Run Flake8 (Linting)
      - name: Lint with Flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings
          flake8 app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # 5. Run Bandit (SAST Security Scan)
      - name: Security Scan with Bandit
        run: |
          # Scan the app directory for common security issues (e.g., hardcoded passwords, SQL injection risks)
          bandit -r app/ -ll -ii

  build-and-scan-image:
    name: Build, Scan (Trivy) and Push
    needs: lint-and-scan # מבטיח שהשלב הזה ירוץ רק אם ה-Lint עבר בהצלחה
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 1. בונים את האימג' אבל שומרים אותו מקומית בשרת של GitHub ולא דוחפים עדיין
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smart-retail-app-api:latest

      # 2. הרצת סורק האבטחה Trivy על האימג' שבנינו
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/smart-retail-app-api:latest'
          format: 'table'
          exit-code: '1' # עוצר את ה-Pipeline אם מצאנו חולשות קריטיות!
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # 3. רק אם Trivy לא מצא חולשות קריטיות נדחוף את האימג' ל-Docker Hub
      - name: Push Docker Image
        if: success()
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smart-retail-app-api:latest
